Feature: Excel Data Reader
  In order to ...
  As a ...
  I want to ...

  Scenario: Excel Data Reader Scenario
    Given The User is at the XXX page of the application
    When The User performs some action using the data from "C:\workspace\IntelliJ_Projects\CucumberTutorial-master\src\main\resources\data_tables\Book1.xlsx"